# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae09689dc4f2c2d3265db3c963ae5378ea931bdecdee9c49fcc6b21bcf5f2903ebd3ee6f871f3f3628eead329c34f070b589a7ed1ed85274410aabcb1c856f0b

test:
  secret_key_base: c9ae048acadebbc9efeb533df9fee69104126d38c2bffab16a15c043633d6430df310555373f3eeb7b73a5079779cda045a50ff8d2d086601ca24ab214d5f756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
